export const getLanguageFromExtension = (ext) => {
    const map = {
        '.js': 'javascript',
        '.jsx': 'javascript',
        '.ts': 'typescript',
        '.tsx': 'typescript',
        '.py': 'python',
        '.rb': 'ruby',
        '.java': 'java',
        '.cpp': 'cpp',
        '.c': 'c',
        '.h': 'c',
        '.cs': 'csharp',
        '.go': 'go',
        '.rs': 'rust',
        '.php': 'php',
        '.html': 'html',
        '.css': 'css',
        '.scss': 'scss',
        '.sass': 'sass',
        '.less': 'less',
        '.json': 'json',
        '.yaml': 'yaml',
        '.yml': 'yaml',
        '.md': 'markdown',
        '.xml': 'xml',
        '.sql': 'sql',
        '.sh': 'bash',
        '.bash': 'bash',
        '.zsh': 'bash',
        '.swift': 'swift',
        '.kt': 'kotlin',
        '.dart': 'dart',
        '.r': 'r',
        '.lua': 'lua',
        '.pl': 'perl',
        '.dockerfile': 'dockerfile',
        'Dockerfile': 'dockerfile',
        '.toml': 'toml',
        '.vue': 'html', // often best highlighted as HTML or specifically vue
        '.svelte': 'html',
    };
    return map[ext.toLowerCase()] || '';
};
